// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_EVENTS_H
#define PICOPIXEL_LVGL_UI_EVENTS_H

#include "screens.h"

#ifdef __cplusplus
extern "C" {
#endif


void pp_anim_stop_timelines_for_deleted_tree(lv_obj_t * root);

/** Wire left/right swipe navigation between screen_1 and screen_2. */
void ui_enable_swipe_navigation(void);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_EVENTS_H*/
