// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_COLORS_H
#define PICOPIXEL_LVGL_UI_COLORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Common colors
extern const uint32_t common_000000;
extern const uint32_t common_008eff;
extern const uint32_t common_08283a;
extern const uint32_t common_0c9bea;
extern const uint32_t common_3d3d3d;
extern const uint32_t common_cad670;
extern const uint32_t common_ea0c0c;
extern const uint32_t common_eadc0c;
extern const uint32_t common_ebc46b;

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_COLORS_H*/
