// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screen_1;
    lv_obj_t *screen_2;
    lv_obj_t *trans_value_label;
    lv_obj_t *fan_pwm_label;
    lv_obj_t *fan_pwm_value_label;
    lv_obj_t *coolant_bar;
    lv_obj_t *voltage_label;
    lv_obj_t *afr_arc;
    lv_obj_t *oil_bar;
    lv_obj_t *afr_label;
    lv_obj_t *label_3;
    lv_obj_t *pcb_temp_label;
    lv_obj_t *trans_label;
    lv_obj_t *coolant_value_label;
    lv_obj_t *title;
    lv_obj_t *pcb_value_label;
    lv_obj_t *iat_temp_bar;
    lv_obj_t *oil_temp_label;
    lv_obj_t *bar_1;
    lv_obj_t *bar_2;
    lv_obj_t *label_1;
    lv_obj_t *rpm_label;
    lv_obj_t *pcb_temp_bar;
    lv_obj_t *oil_value_label;
    lv_obj_t *afr_value_label;
    lv_obj_t *trans_bar;
    lv_obj_t *voltage_value_label;
    lv_obj_t *rpm_value_label;
    lv_obj_t *iat_label;
    lv_obj_t *voltage_bar;
    lv_obj_t *iat_value_label;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREEN_1 = 1,
    SCREEN_ID_SCREEN_2 = 2,
};

void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();
void create_screen_screen_2();
void tick_screen_screen_2();
void delete_screen_screen_2();

/* Keep AFR value + "AFR" caption stacked on the arc circle center. */
void ui_align_afr_readout(void);

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
