// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "colors.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;

void create_screen_screen_1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 1024, 600);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_08283a), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // trans_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.trans_value_label = obj;
            lv_obj_set_pos(obj, 438, 533);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "160 F");
        }
        {
            // coolant_bar
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.coolant_bar = obj;
            lv_obj_set_pos(obj, 20, 396);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 50, 220);
            lv_bar_set_value(obj, 160, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_0c9bea), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 94, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
        {
            // voltage_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.voltage_label = obj;
            lv_obj_set_pos(obj, 61, 100);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 600, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Voltage");
        }
        {
            // afr_arc
            lv_obj_t *obj = lv_arc_create(parent_obj);
            objects.afr_arc = obj;
            lv_obj_set_pos(obj, 596, 96);
            lv_obj_set_size(obj, 448, 392);
            lv_arc_set_bg_angles(obj, 135, 45);
            lv_arc_set_range(obj, 10, 16);
            lv_arc_set_value(obj, 14);
            lv_obj_set_style_arc_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_rounded(obj, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_outline_pad(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_rounded(obj, true, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_color(obj, lv_color_hex(common_008eff), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_cad670), LV_PART_KNOB | LV_STATE_DEFAULT);
            lv_obj_set_style_outline_color(obj, lv_color_hex(common_000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 256, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_outline_width(obj, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_width(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_width(obj, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // oil_bar
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.oil_bar = obj;
            lv_obj_set_pos(obj, 20, 266);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 50, 220);
            lv_bar_set_value(obj, 160, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_0c9bea), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 94, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
        {
            // afr_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.afr_label = obj;
            lv_obj_set_pos(obj, 776, 332);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_pad_top(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "AFR");
        }
        {
            // trans_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.trans_label = obj;
            lv_obj_set_pos(obj, 91, 478);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 600, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Transmission");
        }
        {
            // coolant_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.coolant_value_label = obj;
            lv_obj_set_pos(obj, 438, 417);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "180 F");
        }
        {
            // title
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.title = obj;
            lv_obj_set_pos(obj, 466, 28);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Thunderbird");
        }
        {
            // oil_temp_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.oil_temp_label = obj;
            lv_obj_set_pos(obj, 49, 228);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 600, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Oil ");
        }
        {
            // bar_1
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.bar_1 = obj;
            lv_obj_set_pos(obj, 605, 521);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 0, 5000);
            lv_bar_set_value(obj, 3000, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_eadc0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 128, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 140, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
        {
            // label_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.label_1 = obj;
            lv_obj_set_pos(obj, 62, 357);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 600, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Coolant");
        }
        {
            // rpm_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.rpm_label = obj;
            lv_obj_set_pos(obj, 665, 482);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "RPM");
        }
        {
            // oil_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.oil_value_label = obj;
            lv_obj_set_pos(obj, 438, 287);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "190 F");
        }
        {
            // afr_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.afr_value_label = obj;
            lv_obj_set_pos(obj, 794, 246);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 2000, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ea0c0c), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "14.7");
        }
        {
            // trans_bar
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.trans_bar = obj;
            lv_obj_set_pos(obj, 20, 513);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 50, 220);
            lv_bar_set_value(obj, 160, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_0c9bea), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 94, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
        {
            // voltage_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.voltage_value_label = obj;
            lv_obj_set_pos(obj, 438, 161);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "14V");
        }
        {
            // rpm_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.rpm_value_label = obj;
            lv_obj_set_pos(obj, 891, 481);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "1500");
        }
        {
            // voltage_bar
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.voltage_bar = obj;
            lv_obj_set_pos(obj, 20, 140);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 50, 220);
            lv_bar_set_value(obj, 160, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_0c9bea), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 94, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
    }

    tick_screen_screen_1();
}

void tick_screen_screen_1() {
}


void create_screen_screen_2() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_2 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 1024, 600);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_08283a), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // fan_pwm_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.fan_pwm_label = obj;
            lv_obj_set_pos(obj, 103, 379);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 600, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Fan PWM");
        }
        {
            // fan_pwm_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.fan_pwm_value_label = obj;
            lv_obj_set_pos(obj, 464, 430);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "50 %");
        }
        {
            // label_3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.label_3 = obj;
            lv_obj_set_pos(obj, 464, 177);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "75 F");
        }
        {
            // pcb_temp_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.pcb_temp_label = obj;
            lv_obj_set_pos(obj, 88, 123);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 600, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "PCB");
        }
        {
            // pcb_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.pcb_value_label = obj;
            lv_obj_set_pos(obj, 407, 57);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Thunderbird");
        }
        {
            // iat_temp_bar
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.iat_temp_bar = obj;
            lv_obj_set_pos(obj, 46, 282);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 25, 200);
            lv_bar_set_value(obj, 120, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_0c9bea), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 94, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
        {
            // bar_2
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.bar_2 = obj;
            lv_obj_set_pos(obj, 46, 409);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 0, 100);
            lv_bar_set_value(obj, 50, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_0c9bea), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 94, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
        {
            // pcb_temp_bar
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.pcb_temp_bar = obj;
            lv_obj_set_pos(obj, 46, 156);
            lv_obj_set_size(obj, 372, 57);
            lv_bar_set_range(obj, 25, 100);
            lv_bar_set_value(obj, 75, LV_ANIM_OFF);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_0c9bea), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_bottom(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_top(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_main_stop(obj, 94, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_left(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_pad_right(obj, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_color(obj, lv_color_hex(common_ea0c0c), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_grad_stop(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        }
        {
            // iat_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.iat_label = obj;
            lv_obj_set_pos(obj, 87, 251);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 600, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Intake");
        }
        {
            // iat_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.iat_value_label = obj;
            lv_obj_set_pos(obj, 464, 303);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "120 F");
        }
    }

    tick_screen_screen_2();
}

void tick_screen_screen_2() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_screen_1,
    tick_screen_screen_2,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_screen_1() {
    if (objects.screen_1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_1);
        lv_obj_del(objects.screen_1);
    }
    objects.screen_1 = 0;
    objects.trans_value_label = 0;
    objects.coolant_bar = 0;
    objects.voltage_label = 0;
    objects.afr_arc = 0;
    objects.oil_bar = 0;
    objects.afr_label = 0;
    objects.trans_label = 0;
    objects.coolant_value_label = 0;
    objects.title = 0;
    objects.oil_temp_label = 0;
    objects.bar_1 = 0;
    objects.label_1 = 0;
    objects.rpm_label = 0;
    objects.oil_value_label = 0;
    objects.afr_value_label = 0;
    objects.trans_bar = 0;
    objects.voltage_value_label = 0;
    objects.rpm_value_label = 0;
    objects.voltage_bar = 0;
}

void delete_screen_screen_2() {
    if (objects.screen_2 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_2);
        lv_obj_del(objects.screen_2);
    }
    objects.screen_2 = 0;
    objects.fan_pwm_label = 0;
    objects.fan_pwm_value_label = 0;
    objects.label_3 = 0;
    objects.pcb_temp_label = 0;
    objects.pcb_value_label = 0;
    objects.iat_temp_bar = 0;
    objects.bar_2 = 0;
    objects.pcb_temp_bar = 0;
    objects.iat_label = 0;
    objects.iat_value_label = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_screen_1,
    delete_screen_screen_2,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_screen_1();
    create_screen_screen_2();
}
