// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "colors.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"
#include "segment_bar.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;

/*
 * LVGL draws the arc circle using min(w,h) and left/top pads — not the
 * geometric center of a non-square widget. Align the value + caption as one
 * vertical stack on that true circle center.
 */
void ui_align_afr_readout(void) {
    if (!objects.afr_arc || !objects.afr_value_label || !objects.afr_label) {
        return;
    }

    lv_obj_update_layout(objects.afr_arc);
    lv_obj_update_layout(objects.afr_value_label);
    lv_obj_update_layout(objects.afr_label);

    const lv_coord_t left = lv_obj_get_style_pad_left(objects.afr_arc, LV_PART_MAIN);
    const lv_coord_t right = lv_obj_get_style_pad_right(objects.afr_arc, LV_PART_MAIN);
    const lv_coord_t top = lv_obj_get_style_pad_top(objects.afr_arc, LV_PART_MAIN);
    const lv_coord_t bottom = lv_obj_get_style_pad_bottom(objects.afr_arc, LV_PART_MAIN);
    const lv_coord_t w = lv_obj_get_width(objects.afr_arc);
    const lv_coord_t h = lv_obj_get_height(objects.afr_arc);
    const lv_coord_t r = LV_MIN(w - left - right, h - top - bottom) / 2;

    const lv_coord_t cx = lv_obj_get_x(objects.afr_arc) + left + r;
    const lv_coord_t cy = lv_obj_get_y(objects.afr_arc) + top + r;

    const lv_coord_t vw = lv_obj_get_width(objects.afr_value_label);
    const lv_coord_t vh = lv_obj_get_height(objects.afr_value_label);
    const lv_coord_t lw = lv_obj_get_width(objects.afr_label);
    const lv_coord_t lh = lv_obj_get_height(objects.afr_label);

    const lv_coord_t gap = 4;
    const lv_coord_t stack_h = vh + gap + lh;
    const lv_coord_t stack_top = cy - stack_h / 2;

    lv_obj_set_pos(objects.afr_value_label, cx - vw / 2, stack_top);
    lv_obj_set_pos(objects.afr_label, cx - lw / 2, stack_top + vh + gap);
}

void create_screen_screen_1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 1024, 600);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_08283a), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // trans_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.trans_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "250 F");
        }
        {
            // coolant_bar: blue 50–160, green 160–210, red 210–250
            lv_obj_t *obj = segment_bar_create(parent_obj, 50, 160, 210, 250);
            objects.coolant_bar = obj;
            lv_obj_set_pos(obj, 20, 396);
            lv_obj_set_size(obj, 372, 57);
        }
        {
            // voltage_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.voltage_label = obj;
            lv_obj_set_pos(obj, 20, 90);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Voltage");
        }
        {
            // afr_arc (square so widget center == LVGL circle center)
            lv_obj_t *obj = lv_arc_create(parent_obj);
            objects.afr_arc = obj;
            lv_obj_set_pos(obj, 596, 96);
            lv_obj_set_size(obj, 392, 392);
            lv_arc_set_bg_angles(obj, 135, 45);
            lv_arc_set_range(obj, 100, 180);  /* AFR tenths: 10.0–18.0 */
            lv_arc_set_value(obj, 147);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_opa(obj, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_rounded(obj, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_color(obj, lv_color_hex(common_3d3d3d), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_outline_pad(obj, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_rounded(obj, true, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_color(obj, lv_color_hex(common_008eff), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(obj, lv_color_hex(common_cad670), LV_PART_KNOB | LV_STATE_DEFAULT);
            lv_obj_set_style_outline_color(obj, lv_color_hex(common_000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_zoom(obj, 256, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_outline_width(obj, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_width(obj, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_width(obj, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
            lv_obj_set_style_arc_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // oil_bar: blue 50–180, green 180–220, red 220–250
            lv_obj_t *obj = segment_bar_create(parent_obj, 50, 180, 220, 250);
            objects.oil_bar = obj;
            lv_obj_set_pos(obj, 20, 266);
            lv_obj_set_size(obj, 372, 57);
        }
        {
            // afr_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.afr_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "AFR");
        }
        {
            // trans_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.trans_label = obj;
            lv_obj_set_pos(obj, 20, 468);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Transmission");
        }
        {
            // coolant_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.coolant_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "250 F");
        }
        {
            // title
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.title = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Thunderbird");
            lv_obj_update_layout(obj);
            lv_obj_align(obj, LV_ALIGN_TOP_MID, 0, 16);
        }
        {
            // oil_temp_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.oil_temp_label = obj;
            lv_obj_set_pos(obj, 20, 218);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Oil");
        }
        {
            // bar_1 (RPM): yellow 0–3333, red 3333–5000
            lv_obj_t *obj = segment_bar_create_2zone(parent_obj, 0, 3333, 5000,
                                                     common_eadc0c, common_ea0c0c);
            objects.bar_1 = obj;
            lv_obj_set_pos(obj, 605, 521);
            lv_obj_set_size(obj, 372, 57);
        }
        {
            // label_1
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.label_1 = obj;
            lv_obj_set_pos(obj, 20, 347);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Coolant");
        }
        {
            // rpm_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.rpm_label = obj;
            lv_obj_set_pos(obj, 605, 472);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "RPM");
        }
        {
            // oil_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.oil_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "250 F");
        }
        {
            // afr_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.afr_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_96, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ea0c0c), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "14.7");
        }
        {
            // trans_bar: blue 50–160, green 160–200, red 200–250
            lv_obj_t *obj = segment_bar_create(parent_obj, 50, 160, 200, 250);
            objects.trans_bar = obj;
            lv_obj_set_pos(obj, 20, 513);
            lv_obj_set_size(obj, 372, 57);
        }
        {
            // voltage_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.voltage_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "16.0V");
        }
        {
            // rpm_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.rpm_value_label = obj;
            lv_obj_set_pos(obj, 891, 481);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "1500");
        }
        {
            // voltage_bar (hundredths V): blue 10.0–12.0, green 12.0–15.0, red 15.0–16.0
            lv_obj_t *obj = segment_bar_create(parent_obj, 1000, 1200, 1500, 1600);
            objects.voltage_bar = obj;
            lv_obj_set_pos(obj, 20, 140);
            lv_obj_set_size(obj, 372, 57);
        }

        /* Place value labels 10px past each bar, vertically centered. */
        lv_obj_align_to(objects.voltage_value_label, objects.voltage_bar, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
        lv_obj_align_to(objects.oil_value_label, objects.oil_bar, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
        lv_obj_align_to(objects.coolant_value_label, objects.coolant_bar, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
        lv_obj_align_to(objects.trans_value_label, objects.trans_bar, LV_ALIGN_OUT_RIGHT_MID, 10, 0);

        /* Center AFR value + caption on the arc circle (not the widget box). */
        lv_obj_update_layout(objects.screen_1);
        ui_align_afr_readout();
    }

    tick_screen_screen_1();
}

void tick_screen_screen_1() {
}


static void style_metric_label(lv_obj_t *obj) {
    lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(obj, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
}

void create_screen_screen_2() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_2 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 1024, 600);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_08283a), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // pcb_value_label (page title — same as screen_1)
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.pcb_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ebc46b), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Thunderbird");
            lv_obj_update_layout(obj);
            lv_obj_align(obj, LV_ALIGN_TOP_MID, 0, 16);
        }
        {
            // pcb_temp_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.pcb_temp_label = obj;
            lv_obj_set_pos(obj, 20, 90);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            style_metric_label(obj);
            lv_label_set_text(obj, "PCB");
        }
        {
            // pcb_temp_bar: blue 25–70, green 70–100, red 100–120
            lv_obj_t *obj = segment_bar_create(parent_obj, 25, 70, 100, 120);
            objects.pcb_temp_bar = obj;
            lv_obj_set_pos(obj, 20, 140);
            lv_obj_set_size(obj, 372, 57);
        }
        {
            // label_3 (PCB value)
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.label_3 = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            style_metric_label(obj);
            lv_label_set_text(obj, "120 F");
        }
        {
            // iat_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.iat_label = obj;
            lv_obj_set_pos(obj, 20, 218);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            style_metric_label(obj);
            lv_label_set_text(obj, "Intake");
        }
        {
            // iat_temp_bar: blue 25–100, green 100–140, red 140–200
            lv_obj_t *obj = segment_bar_create(parent_obj, 25, 100, 140, 200);
            objects.iat_temp_bar = obj;
            lv_obj_set_pos(obj, 20, 266);
            lv_obj_set_size(obj, 372, 57);
        }
        {
            // iat_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.iat_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            style_metric_label(obj);
            lv_label_set_text(obj, "200 F");
        }
        {
            // fan_pwm_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.fan_pwm_label = obj;
            lv_obj_set_pos(obj, 20, 347);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            style_metric_label(obj);
            lv_label_set_text(obj, "Fan PWM");
        }
        {
            // bar_2 (fan PWM): blue 0–30, green 30–70, red 70–100
            lv_obj_t *obj = segment_bar_create(parent_obj, 0, 30, 70, 100);
            objects.bar_2 = obj;
            lv_obj_set_pos(obj, 20, 396);
            lv_obj_set_size(obj, 372, 57);
        }
        {
            // fan_pwm_value_label
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.fan_pwm_value_label = obj;
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            style_metric_label(obj);
            lv_label_set_text(obj, "100 %");
        }

        /* Same value placement as screen_1: 10px past each bar, vertically centered. */
        lv_obj_align_to(objects.label_3, objects.pcb_temp_bar, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
        lv_obj_align_to(objects.iat_value_label, objects.iat_temp_bar, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
        lv_obj_align_to(objects.fan_pwm_value_label, objects.bar_2, LV_ALIGN_OUT_RIGHT_MID, 10, 0);
    }

    tick_screen_screen_2();
}

void tick_screen_screen_2() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_screen_1,
    tick_screen_screen_2,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_screen_1() {
    if (objects.screen_1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_1);
        lv_obj_del(objects.screen_1);
    }
    objects.screen_1 = 0;
    objects.trans_value_label = 0;
    objects.coolant_bar = 0;
    objects.voltage_label = 0;
    objects.afr_arc = 0;
    objects.oil_bar = 0;
    objects.afr_label = 0;
    objects.trans_label = 0;
    objects.coolant_value_label = 0;
    objects.title = 0;
    objects.oil_temp_label = 0;
    objects.bar_1 = 0;
    objects.label_1 = 0;
    objects.rpm_label = 0;
    objects.oil_value_label = 0;
    objects.afr_value_label = 0;
    objects.trans_bar = 0;
    objects.voltage_value_label = 0;
    objects.rpm_value_label = 0;
    objects.voltage_bar = 0;
}

void delete_screen_screen_2() {
    if (objects.screen_2 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_2);
        lv_obj_del(objects.screen_2);
    }
    objects.screen_2 = 0;
    objects.fan_pwm_label = 0;
    objects.fan_pwm_value_label = 0;
    objects.label_3 = 0;
    objects.pcb_temp_label = 0;
    objects.pcb_value_label = 0;
    objects.iat_temp_bar = 0;
    objects.bar_2 = 0;
    objects.pcb_temp_bar = 0;
    objects.iat_label = 0;
    objects.iat_value_label = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_screen_1,
    delete_screen_screen_2,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_screen_1();
    create_screen_screen_2();
}
